### ISSUE TITLE
Could not create my-new-func function with template HTTP trigger. Error: No files were found to copy

### ISSUE THREAD

**Issue by michal-husak** [AlexPshul/nxazure#28]
```shell
npx create-nx-workspace@latest audit-logs-nx-plugin-monorepo

Need to install the following packages:
create-nx-workspace@17.1.1
Ok to proceed? (y) y

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Which stack do you want to use? · none
✔ Package-based monorepo, integrated monorepo, or standalone project? · integrated
✔ Enable distributed caching to make your CI faster · No

 >  NX   Creating your v17.1.1 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "npm install" several times. Please wait.

✔ Installing dependencies with npm
✔ Successfully created the workspace: audit-logs-nx-plugin-monorepo.
```

```shell
cd audit-logs-nx-plugin-monorepo
```

```shell
npm install -D @nxazure/func
```

```shell
nx g @nxazure/func:init my-new-app

>  NX  Generating @nxazure/func:init

ATTENTION Some dependencies might not work well together. If something is not working, try to update @types/node, typescript or @azure/functions to the latest (preview for V4) versions.

removed 2 packages, and audited 418 packages in 648ms

47 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
CREATE my-new-app/project.json
UPDATE .vscode/extensions.json
UPDATE package.json
CREATE my-new-app/tsconfig.json
CREATE my-new-app/tsconfig.build.json
CREATE tsconfig.base.json
CREATE my-new-app/package.json
CREATE my-new-app/host.json
CREATE my-new-app/local.settings.json
CREATE my-new-app/.funcignore
CREATE my-new-app/_registerPaths.ts
```

```shell
nx g @nxazure/func:new my-new-func --project=my-new-app --template="HTTP trigger"

>  NX  Generating @nxazure/func:new

Could not create my-new-func function with template HTTP trigger. Error: No files were found to copy
    at copyFiles (/Users/xxx/dev/xxx-nx-plugin-monorepo/node_modules/@nxazure/func/src/generators/new/generator.js:41:15)
    at /Users/xxx/dev/xxx-nx-plugin-monorepo/node_modules/@nxazure/func/src/generators/new/generator.js:69:13
    at Generator.next (<anonymous>)
    at /Users/xxx/dev/xxx-nx-plugin-monorepo/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/xxx/dev/xxx-nx-plugin-monorepo/node_modules/tslib/tslib.js:165:16)
    at default_1 (/Users/xxx/dev/xxx-nx-plugin-monorepo/node_modules/@nxazure/func/src/generators/new/generator.js:57:20)
    at /Users/xxx/dev/xxx-nx-plugin-monorepo/node_modules/nx/src/command-line/generate/generate.js:241:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleErrors (/Users/xxx/dev/xxx-nx-plugin-monorepo/node_modules/nx/src/utils/params.js:9:16)

 >  NX   No files were found to copy

   Pass --verbose to see the stacktrace.
```

I created the workspace for integrated monorepo and for typescript.

I also updated the packages:
`@types/node` 18.18.9
`@azure/functions` 4.0.1

Any idea what I am doing wrong? 

Thank you.

**Comment by AlexPshul** [comment]
Hi @michal-husak,
I am currently working on adjusting the package to the new V4 version of azure functions.
It looks like the latest change in the tools broke some functionality.
I'll ping here once the new version is out.

**Comment by AlexPshul** [comment]
Please try again with version 1.1.0 and the latest Azure function tools and reopen the issue if this happens again.
